blank_issues_enabled: false
contact_links:
  - name: Home Assistant Community
    url: https://community.home-assistant.io/
    about: General questions about Home Assistant, automations and blueprints.
  - name: Home Assistant blueprint documentation
    url: https://www.home-assistant.io/docs/automation/using_blueprints/
    about: How to import blueprints and create automations from them.
